### ISSUE TITLE
Undefined offset: 2 in Sanitize.php

### ISSUE THREAD

**Issue by JanPetterMG** [simplepie/simplepie#441]
``Notice: Undefined offset: 2 in /library/SimplePie/Sanitize.php on line 372``

This notice shows up in the logs every 5 minute. Haven't been able to find out what feed yet, but I'll let you know once I find out...

I'm using ``1.4 beta``
Haven't tested in ``1.3.1`` (yet), I'm about to migrate to simplepie...

-----------------------

```php
list($_, $data, $_) = explode($unique_tag, $data);
```
https://github.com/simplepie/simplepie/blob/master/library/SimplePie/Sanitize.php#L372

**Comment by JanPetterMG** [comment]
**Here are the problematic URLs:** (the list will be updated as I discover them)
http://m.lubbockonline.com/taxonomy/term/240886/2/feed
http://podkast.nrk.no/program/ekko_-_et_aktuelt_samfunnsprogram.rss

**Comment by droplister** [comment]
I am also getting this issue with some feeds. Here's some snippets from my error log. I am using Laravel.

```
[2016-05-10 21:54:55] local.ERROR: exception 'ErrorException' with message 'Undefined offset: 2' in /var/www/rssmixer.com/vendor/simplepie/simplepie/library/SimplePie/Sanitize.php:372
Stack trace:
#0 /var/www/rssmixer.com/vendor/simplepie/simplepie/library/SimplePie/Sanitize.php(372): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined offse...', '/var/www/rssmix...', 372, Array)
#1 /var/www/rssmixer.com/vendor/simplepie/simplepie/library/SimplePie.php(2118): SimplePie_Sanitize->sanitize('<p>&nbsp;</p>??...', 2, 'http://share.dm...')
#2 /var/www/rssmixer.com/vendor/simplepie/simplepie/library/SimplePie/Item.php(181): SimplePie->sanitize('<p>&nbsp;</p>??...', 2, 'http://share.dm...')
#3 /var/www/rssmixer.com/vendor/simplepie/simplepie/library/SimplePie/Item.php(323): SimplePie_Item->sanitize('<p>&nbsp;</p>??...', 2, 'http://share.dm...')
```

Although these probably aren't that helpful...

```
[2016-05-10 21:41:42] local.ERROR: exception 'ErrorException' with message 'Undefined offset: 2' in /var/www/rssmixer.com/vendor/simplepie/simplepie/library/SimplePie/Sanitize.php:372
Stack trace:
#0 /var/www/rssmixer.com/vendor/simplepie/simplepie/library/SimplePie/Sanitize.php(372): Illuminate\Foundation\Bootstrap\HandleExceptions->handleError(8, 'Undefined offse...', '/var/www/rssmix...', 372, Array)
#1 /var/www/rssmixer.com/vendor/simplepie/simplepie/library/SimplePie.php(2118): SimplePie_Sanitize->sanitize('<a href="https:...', 2, 'http://facebook...')
#2 /var/www/rssmixer.com/vendor/simplepie/simplepie/library/SimplePie/Item.php(181): SimplePie->sanitize('<a href="https:...', 2, 'http://facebook...')
#3 /var/www/rssmixer.com/vendor/simplepie/simplepie/library/SimplePie/Item.php(323): SimplePie_Item->sanitize('<a href="https:...', 2, 'http://facebook...')
#4 /var/www/rssmixer.com/storage/framework/views/12c05142c8e737df857d882f714e267fc2c7d772.php(18): SimplePie_Item->get_description()
```

**Comment by droplister** [comment]
I just ended up wrapping $item->get_description() in a try/catch, so if this error occurs I show a "Description could not be retrieved."

**Comment by JanPetterMG** [comment]
A good work-around. Implementing it me too now, but with a empty string instead :-)

**Comment by mblaney** [comment]
fixed
