### ISSUE TITLE
 get_enclosures() returns only the first enclosure

### ISSUE THREAD

**Issue by aberbenni** [simplepie/simplepie#585]
I'm usting SP 1.3.1 in WP 4.9.6 working on a feed that hase multiple enclosure in one item.

With `echo ''.print_r($item,true).''` I can see the array of two elements:

```
[enclosure] =&gt; Array
 (
     [0] =&gt; Array
         (
             [data] =&gt; 
             [attribs] =&gt; Array
                 (
                     [] =&gt; Array
                         (
                             [url] =&gt; http://www.example.com/wp-content/uploads/2018/05/file.mp3
                             [length] =&gt; 5285091
                             [type] =&gt; audio/mpeg
                         )

                 )

             [xml_base] =&gt; 
             [xml_base_explicit] =&gt; 
             [xml_lang] =&gt; 
         )

     [1] =&gt; Array
         (
             [data] =&gt; 
             [attribs] =&gt; Array
                 (
                     [] =&gt; Array
                         (
                             [url] =&gt; https://www.example.com/wp-content/uploads/2018/05/image.jpg
                             [length] =&gt; 84735
                             [type] =&gt; image/jpeg
                         )

                 )

             [xml_base] =&gt; 
             [xml_base_explicit] =&gt; 
             [xml_lang] =&gt; 
         )

 )                                                                                                                                
```

But with this:

```
foreach ($item->get_enclosures(0,0) as $enclosure) {
   echo $enclosure->get_type();
}
```

it only prints `audio/mpeg` (same with `get_enclosures()`).

I would like to get the image an not the mp3.

**Comment by aberbenni** [comment]
With this code:

```
225		if( $item->get_enclosure(0)->get_type() == 'audio/mpeg') {
226			echo $item->get_enclosure(1)->get_type();
227		}
```

The error is:

```
[25-May-2018 09:01:48 UTC] PHP Fatal error:  Uncaught Error: Call to a member function get_type() on null in /wp-content/mu-plugins/nb-rss.php:226
Stack trace:
#0 /wp-content/mu-plugins/nb-rss.php(77): nb_widget_rss_output(Object(SimplePie), Array)
#1 /wp-includes/class-wp-widget.php(372): NB_Widget_RSS->widget(Array, Array)
#2 /wp-content/plugins/amr-shortcode-any-widget/amr-shortcode-any-widget.php(318): WP_Widget->display_callback(Array, Array)
#3 /wp-content/plugins/amr-shortcode-any-widget/amr-shortcode-any-widget.php(209): amr_shortcode_sidebar('nb-rss-2', 'Widgets for Sho...', '', 'amr_widget', '', '')
#4 /wp-includes/shortcodes.php(319): amr_do_widget(Array, '', 'do_widget')
#5 [internal function]: do_shortcode_tag(Array)
#6 /wp-includes/shortcodes.php(197): preg_replace_callback('/\\[(\\[?)(do_wid...', 'do_shor in /wp-content/mu-plugins/nb-rss.php on line 226
```

Enclosure 1 does not exist, but printing the array I can see it:

```
[1] =&gt; Array
         (
             [data] =&gt; 
             [attribs] =&gt; Array
                 (
                     [] =&gt; Array
                         (
                             [url] =&gt; https://www.example.com/wp-content/uploads/2018/05/image.jpg
                             [length] =&gt; 84735
                             [type] =&gt; image/jpeg
                         )

                 )

             [xml_base] =&gt; 
             [xml_base_explicit] =&gt; 
             [xml_lang] =&gt; 
         )
```

**Comment by aberbenni** [comment]
`echo ''.print_r($item->get_enclosures(0,0),true).'';`

`Array ( [0] => SimplePie_Enclosure Object ( [bitrate] => [captions] => [categories] => [channels] => [copyright] => [credits] => [description] => [duration] => [expression] => [framerate] => [handler] => mp3 [hashes] => [height] => [javascript] => [keywords] => [lang] => [length] => 5285091 [link] => http://www.example.com/wp-content/uploads/2018/05/file.mp3 [medium] => [player] => [ratings] => [restrictions] => Array ( [0] => SimplePie_Restriction Object ( [relationship] => allow [type] => [value] => default ) ) [samplingrate] => [thumbnails] => [title] => [type] => audio/mpeg [width] => ) ) `

**Comment by aberbenni** [comment]
Here is an orrible patch, using `$item->get_item_tags(SIMPLEPIE_NAMESPACE_RSS_20, 'enclosure');`


```
$enclosures = $item->get_item_tags(SIMPLEPIE_NAMESPACE_RSS_20, 'enclosure');
$enclosure_url = "#";
if(sizeof($enclosures)>1) {
	foreach ($enclosures as $enclosure) {
		$enclosure_attribs = array_values($enclosure['attribs'])[0];
		if (stripos($enclosure_attribs['type'], 'image') !== false) {
			$enclosure_url =$enclosure_attribs['url'];
		}
	}
} else {
	$enclosure_url = $item->get_enclosure(0)->get_link();
}
```

**Comment by aberbenni** [comment]
This is the version distributed with WP 4.9.6 https://github.com/WordPress/WordPress/blob/194d534babe8e164fc32cd83d985a7167bd0f390/wp-includes/SimplePie/Enclosure.php

**Comment by DrLightman** [comment]
Thank you very much for the patch, I was starting to shit my pants as I went through a bug where only the first enclosure was returned (a video), whilst I needed the second (an image).

**Comment by BorisAnthony** [comment]
Wordpress 5.7.2 now and though the SimplePie/Enclosure.php file has a few changes, it still only returns the first enclosure, no matter if you call get_enclosures() or get_enclosure($key). Crazy.
