### ISSUE TITLE
[BUG] PHP Fatal error:  Uncaught TypeError: strspn(): Argument #1 ($string) must be of type string, null given in /var/www/vhosts/xxx/framework/simplepie/src/Content/Type/Sniffer.php:153

### ISSUE THREAD

**Issue by thE-iNviNciblE** [simplepie/simplepie#810]
> **IMPORTANT:** If you are posting code or output, please make sure you wrap it with [fenced code blocks](https://help.github.com/articles/creating-and-highlighting-code-blocks/) so that it is readable.

#### Description

`$ws = strspn($this->file->body, "\x09\x0A\x0B\x0C\x0D\x20");` - simplepie/src/Content/Type/Sniffer.php:153

$this->file->body is empty.

#### Steps to Reproduce

it's maybe a empty resource where the DOM HTML is empty.

#### Expected Behavior

skip invalid RSS-Source.

#### Actual Behavior

Fatal error cron job exits.

#### Possible Solutions

strlen() Check should work to avoid strspn() to crash.
```
        if(strlen($this->file->body) != 0) {
        
            $ws = strspn($this->file->body, "\x09\x0A\x0B\x0C\x0D\x20");
            if (strtolower(substr($this->file->body, $ws, 14)) === '<!doctype html'
                || strtolower(substr($this->file->body, $ws, 5)) === '<html'
                || strtolower(substr($this->file->body, $ws, 7)) === '<script') {
                return 'text/html';
            } elseif (substr($this->file->body, 0, 5) === '%PDF-') {
                return 'application/pdf';
            } elseif (substr($this->file->body, 0, 11) === '%!PS-Adobe-') {
                return 'application/postscript';
            } elseif (substr($this->file->body, 0, 6) === 'GIF87a'
                || substr($this->file->body, 0, 6) === 'GIF89a') {
                return 'image/gif';
            } elseif (substr($this->file->body, 0, 8) === "\x89\x50\x4E\x47\x0D\x0A\x1A\x0A") {
                return 'image/png';
            } elseif (substr($this->file->body, 0, 3) === "\xFF\xD8\xFF") {
                return 'image/jpeg';
            } elseif (substr($this->file->body, 0, 2) === "\x42\x4D") {
                return 'image/bmp';
            } elseif (substr($this->file->body, 0, 4) === "\x00\x00\x01\x00") {
                return 'image/vnd.microsoft.icon';
            }
            
            return $this->text_or_binary();
        }
```

#### Environment

Debian 10 with PHP 8.2

**Comment by jtojnar** [comment]
Thanks for reporting. Do you have the error message? `strspn` should be fine with an empty string.

**Comment by jtojnar** [comment]
Oh, never mind, it is in the title. Ugh, we should really have checked the codebase with PHPStan before releasing with `strict_deps`.

Perhaps initializing the body to an empty string here will work as a stop gap:

https://github.com/simplepie/simplepie/blob/7b0901cd46292a40cf0be258d1e1582f4a7b3597/src/File.php#L62

This part of the code will be re-done with #774 so that will hopefully fix it properly.

**Comment by thE-iNviNciblE** [comment]
> Oh, never mind, it is in the title. Ugh, we should really have checked the codebase with PHPStan before releasing with `strict_deps`.
> 
> Perhaps initializing the body to an empty string here will work as a stop gap:
> 
> https://github.com/simplepie/simplepie/blob/7b0901cd46292a40cf0be258d1e1582f4a7b3597/src/File.php#L62
> 
> This part of the code will be re-done with #774 so that will hopefully fix it properly.

it's a PHP 8.2 thing,  It should work with `public $body="";` it's a better solution. 

PHP Fatal error:  Uncaught TypeError: strspn(): Argument #1 ($string) must be of type string, null given in /simplepie/src/Content/Type/Sniffer.php:153
Stack trace:
#0 /simplepie/src/Content/Type/Sniffer.php(153): strspn()
#1 /simplepie/src/Content/Type/Sniffer.php(124): SimplePie\Content\Type\Sniffer->unknown()
#2 /simplepie/src/Locator.php(148): SimplePie\Content\Type\Sniffer->get_type()
#3 /simplepie/src/SimplePie.php(1834): SimplePie\Locator->is_feed()
#4 /simplepie/src/SimplePie.php(1591): SimplePie\SimplePie->fetch_data()
#5 /simplepie/src/SimplePie.php(1564): SimplePie\SimplePie->init()

**Comment by sarahjcotton** [comment]
Hello, are you able to provide any indication of when this might be fixed please?

**Comment by jtojnar** [comment]
It should have been resolved by https://github.com/simplepie/simplepie/releases/tag/1.8.1. Are you still able to reproduce it?

**Comment by LaKanDoR** [comment]
1.8.1 seems to be stable, the error is gone
