### ISSUE TITLE
[BUG] PHP Fatal error: Uncaught TypeError in Sanitize::replace_urls due to a link without host

### ISSUE THREAD

**Issue by blat** [simplepie/simplepie#831]
#### Description

SimplePie is unable to parse this feed: http://www.remodelista.com/feed/

#### Steps to Reproduce

```
$url = 'http://www.remodelista.com/feed/';
$xml = file_get_contents($url);
$parser = new Nv_SimplePie();
$parser->set_raw_data($xml);
$parser->init();
$parser->set_feed_url($url);
foreach ($parser->get_items() as $item) {
    $item->get_content();
}
```

#### Expected Behavior

Be able to parse content of each items

#### Actual Behavior

```
Fatal error: Uncaught TypeError: trim(): Argument #1 ($string) must be of type string, bool given in src/Sanitize.php:319
Stack trace:
#0 src/Sanitize.php(319): trim()
#1 src/Sanitize.php(339): SimplePie\Sanitize->is_https_domain()
#2 src/Sanitize.php(511): SimplePie\Sanitize->https_url()
#3 src/Sanitize.php(414): SimplePie\Sanitize->replace_urls()
#4 src/SimplePie.php(2307): SimplePie\Sanitize->sanitize()
#5 src/Item.php(189): SimplePie\SimplePie->sanitize()
#6 src/Item.php(355): SimplePie\Item->sanitize()
```

#### Analysis

It's due to this item: https://gist.github.com/blat/dd578643ffb45cae8f510fef275404b2 which contains this tag: `<a class="tracked-click" href="http://" target="_blank" rel="noopener">Climbing Curio</a>`

Host is `null`. Trimming a `null` host provides a `TypeError`.

#### Environment

I'm using PHP 8.2

**Comment by jtojnar** [comment]
Thanks for the detailed report. I opened #832
